export interface DetailedExercise {
  id: string;
  name: string;
  category: "Strength" | "Cardio" | "Core" | "Mobility";
  bodyPart: "Chest" | "Legs" | "Full Body" | "Back" | "Shoulders" | "Arms";
  targetMuscles: string;
  secondaryMuscles?: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  equipment: "No equipment" | "Chair" | "Wall" | "Backpack" | "Resistance band";
  startingPosition: string;
  movementPattern: string;
  executionSteps: string[];
  tempo: string;
  recommendedReps?: number;
  recommendedDuration?: number;
  safetyNotes: string;
  commonMistakes: string[];
  contraindications: string[];
  status: "approved" | "pending" | "rejected";
  cameraPreset: "three_quarter" | "front" | "side";
  animationType: "pushup" | "squat" | "plank" | "lunge" | "jumping_jacks" | "burpee" | "crunch" | "mountain_climbers" | "stretching";
}

export const DETAILED_EXERCISE_DATABASE: DetailedExercise[] = [
  // ==================== CHEST ====================
  {
    id: "pushups",
    name: "Standard Push-Up",
    category: "Strength",
    bodyPart: "Chest",
    targetMuscles: "Pectoralis Major, Triceps Brachii, Anterior Deltoids",
    secondaryMuscles: "Rectus Abdominis, Serratus Anterior",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Plank position on hands and toes, hands under shoulders, spine neutral.",
    movementPattern: "Horizontal push & descent",
    executionSteps: [
      "1. Place hands shoulder-width apart with fingers pointing forward.",
      "2. Brace core and squeeze glutes to lock hips in a straight line.",
      "3. Bend elbows at 45 degrees to lower chest until 2 inches above floor.",
      "4. Drive through palms to press back up without arching lower back.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 12,
    safetyNotes: "Keep core locked. Avoid hip sagging or neck hyperextension.",
    commonMistakes: ["Flaring elbows to 90 degrees", "Sagging hips", "Short range of motion"],
    contraindications: ["Acute wrist sprain", "Severe shoulder impingement"],
    status: "approved",
    cameraPreset: "three_quarter",
    animationType: "pushup",
  },
  {
    id: "wide_pushups",
    name: "Wide-Grip Push-Up",
    category: "Strength",
    bodyPart: "Chest",
    targetMuscles: "Outer Pectoralis Major, Anterior Deltoids",
    secondaryMuscles: "Triceps Brachii, Serratus Anterior",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Plank position with hands placed wider than shoulder-width.",
    movementPattern: "Horizontal wide push & descent",
    executionSteps: [
      "1. Place hands wider than shoulder-width apart.",
      "2. Lower chest toward floor by bending elbows outward.",
      "3. Push back up to full arm extension.",
      "4. Keep hips level throughout the movement.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Do not flare elbows past 75 degrees to protect shoulder joint.",
    commonMistakes: ["Elbows flaring too wide", "Hips dropping", "Half reps"],
    contraindications: ["Shoulder impingement", "Rotator cuff injury"],
    status: "approved",
    cameraPreset: "front",
    animationType: "pushup",
  },
  {
    id: "decline_pushups",
    name: "Decline Push-Up",
    category: "Strength",
    bodyPart: "Chest",
    targetMuscles: "Upper Pectoralis Major, Anterior Deltoids",
    secondaryMuscles: "Triceps Brachii, Core",
    difficulty: "Advanced",
    equipment: "No equipment",
    startingPosition: "Feet elevated on a sturdy surface, hands on floor under shoulders.",
    movementPattern: "Decline horizontal push",
    executionSteps: [
      "1. Place feet on a raised surface (chair, step).",
      "2. Hands under shoulders in plank position.",
      "3. Lower upper body toward floor bending elbows.",
      "4. Press back up to starting position.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Ensure the elevated surface is stable. Keep core tight.",
    commonMistakes: ["Sagging hips", "Rushing the descent", "Neck craning"],
    contraindications: ["High blood pressure", "Wrist injuries"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },
  {
    id: "diamond_pushups",
    name: "Diamond Push-Up",
    category: "Strength",
    bodyPart: "Chest",
    targetMuscles: "Inner Pectoralis Major, Triceps Brachii",
    secondaryMuscles: "Anterior Deltoids, Core",
    difficulty: "Advanced",
    equipment: "No equipment",
    startingPosition: "Plank position with hands together forming a diamond shape under chest.",
    movementPattern: "Close-grip horizontal push",
    executionSteps: [
      "1. Place thumbs and index fingers together under chest forming a diamond.",
      "2. Lower body until chest nearly touches hands.",
      "3. Press back up squeezing chest at the top.",
      "4. Keep elbows close to body throughout.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Keep elbows tracking close to ribs. Do not flare.",
    commonMistakes: ["Elbows flaring out", "Hips sagging", "Not going deep enough"],
    contraindications: ["Severe tricep tendonitis", "Wrist pain"],
    status: "approved",
    cameraPreset: "front",
    animationType: "pushup",
  },
  {
    id: "archer_pushups",
    name: "Archer Push-Up",
    category: "Strength",
    bodyPart: "Chest",
    targetMuscles: "Pectoralis Major, Triceps Brachii",
    secondaryMuscles: "Core, Anterior Deltoids",
    difficulty: "Advanced",
    equipment: "No equipment",
    startingPosition: "Wide plank position with hands far apart.",
    movementPattern: "Unilateral horizontal push",
    executionSteps: [
      "1. Place hands wider than shoulder-width.",
      "2. Shift body to one side, bending that elbow while keeping the other arm straight.",
      "3. Lower until chest is near the bent arm's hand.",
      "4. Push back to center and repeat on the other side.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 8,
    safetyNotes: "Only go as low as your strength allows. Keep the straight arm locked.",
    commonMistakes: ["Bending the straight arm", "Rushing the movement", "Hip rotation"],
    contraindications: ["Shoulder instability", "Elbow injuries"],
    status: "approved",
    cameraPreset: "front",
    animationType: "pushup",
  },
  {
    id: "hindu_pushups",
    name: "Hindu Push-Up",
    category: "Strength",
    bodyPart: "Chest",
    targetMuscles: "Pectoralis Major, Shoulders, Triceps",
    secondaryMuscles: "Spinal Erectors, Hamstrings, Core",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Downward dog position with hips high.",
    movementPattern: "Swooping push with spinal extension",
    executionSteps: [
      "1. Start in downward dog with hips elevated.",
      "2. Bend elbows and swoop chest forward and down, skimming the floor.",
      "3. Press up into upward dog, arching the back.",
      "4. Push hips back up to downward dog.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 10,
    safetyNotes: "Keep the swooping motion smooth. Do not jerk the spine.",
    commonMistakes: ["Skipping the swoop", "Rushing through reps", "Lower back pain from poor form"],
    contraindications: ["Lumbar disc herniation", "Severe shoulder pain"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },

  // ==================== ARMS ====================
  {
    id: "tricep_dips_chair",
    name: "Tricep Dips (Chair)",
    category: "Strength",
    bodyPart: "Arms",
    targetMuscles: "Triceps Brachii",
    secondaryMuscles: "Anterior Deltoids, Pectoralis Major",
    difficulty: "Beginner",
    equipment: "Chair",
    startingPosition: "Hands on edge of chair behind you, legs extended or bent.",
    movementPattern: "Vertical dip & press",
    executionSteps: [
      "1. Sit on edge of chair, place hands next to hips gripping the edge.",
      "2. Slide hips off the chair with legs extended or knees bent.",
      "3. Lower body by bending elbows to 90 degrees.",
      "4. Press through palms to extend arms back up.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 12,
    safetyNotes: "Keep elbows pointing backward, not flared. Shoulders stay down.",
    commonMistakes: ["Elbows flaring outward", "Going too deep", "Shrugging shoulders"],
    contraindications: ["Shoulder impingement", "Elbow bursitis"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },
  {
    id: "close_grip_pushups",
    name: "Close-Grip Push-Up",
    category: "Strength",
    bodyPart: "Arms",
    targetMuscles: "Triceps Brachii, Inner Chest",
    secondaryMuscles: "Anterior Deltoids, Core",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Plank with hands shoulder-width apart directly under chest.",
    movementPattern: "Close-grip horizontal push",
    executionSteps: [
      "1. Hands shoulder-width apart under chest.",
      "2. Lower body bending elbows close to ribs.",
      "3. Press back up squeezing triceps at top.",
      "4. Keep body rigid throughout.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 12,
    safetyNotes: "Keep elbows tight to body. Do not let hips sag.",
    commonMistakes: ["Elbows flaring", "Hips piking up", "Incomplete range"],
    contraindications: ["Tricep tendinitis", "Wrist strain"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },
  {
    id: "plank_updowns",
    name: "Plank Up-Downs",
    category: "Strength",
    bodyPart: "Arms",
    targetMuscles: "Triceps Brachii, Core, Shoulders",
    secondaryMuscles: "Chest, Obliques",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Forearm plank position.",
    movementPattern: "Alternating arm press from forearm to hand plank",
    executionSteps: [
      "1. Start in forearm plank on elbows.",
      "2. Press right hand into floor to extend right arm.",
      "3. Follow with left arm to reach high plank position.",
      "4. Lower back down one arm at a time to forearm plank.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Keep hips as still as possible. Alternate which arm leads.",
    commonMistakes: ["Excessive hip rocking", "Rushing the movement", "Letting hips sag"],
    contraindications: ["Wrist injuries", "Severe core weakness"],
    status: "approved",
    cameraPreset: "side",
    animationType: "mountain_climbers",
  },
  {
    id: "tricep_extensions",
    name: "Bodyweight Tricep Extension",
    category: "Strength",
    bodyPart: "Arms",
    targetMuscles: "Triceps Brachii",
    secondaryMuscles: "Core, Shoulders",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Hands on an elevated surface (couch, step), body at an incline.",
    movementPattern: "Elbow flexion & extension at incline",
    executionSteps: [
      "1. Place hands on a stable elevated surface, arms straight.",
      "2. Walk feet back so body is at an incline.",
      "3. Bend elbows to lower head below hand level.",
      "4. Press through palms to extend arms back to start.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Keep elbows tucked in. Do not let elbows flare.",
    commonMistakes: ["Elbows drifting outward", "Not going deep enough", "Arching back"],
    contraindications: ["Severe elbow pain", "Tricep tear history"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },
  {
    id: "shoulder_tap_pushup",
    name: "Push-Up to Shoulder Tap",
    category: "Strength",
    bodyPart: "Arms",
    targetMuscles: "Triceps, Chest, Core Stability",
    secondaryMuscles: "Anterior Deltoids, Obliques",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Standard push-up plank position.",
    movementPattern: "Push-up with unilateral shoulder tap",
    executionSteps: [
      "1. Perform a standard push-up.",
      "2. At the top, lift right hand to tap left shoulder.",
      "3. Return hand to floor and perform another push-up.",
      "4. At the top, tap right shoulder with left hand.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Minimize hip rotation during the shoulder tap.",
    commonMistakes: ["Excessive hip sway", "Rushing through reps", "Poor push-up depth"],
    contraindications: ["Shoulder instability", "Core injuries"],
    status: "approved",
    cameraPreset: "three_quarter",
    animationType: "pushup",
  },

  // ==================== LEGS ====================
  {
    id: "air_squats",
    name: "Bodyweight Deep Squat",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Quadriceps, Gluteus Maximus, Hamstrings",
    secondaryMuscles: "Calves, Erector Spinae",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Feet shoulder-width apart, toes turned slightly outward, chest tall.",
    movementPattern: "Vertical knee-hip flexion",
    executionSteps: [
      "1. Stand tall with feet grounded, heels glued to floor.",
      "2. Hinge at hips and bend knees simultaneously.",
      "3. Descend until thighs are parallel or below knee crease.",
      "4. Push through mid-foot and heels to drive back up.",
    ],
    tempo: "3-1-1-1",
    recommendedReps: 15,
    safetyNotes: "Ensure knees track in line with toes without collapsing inward.",
    commonMistakes: ["Knees collapsing inward", "Heels lifting off floor", "Rounding lower back"],
    contraindications: ["Acute knee ligament strain", "Severe hip bursitis"],
    status: "approved",
    cameraPreset: "three_quarter",
    animationType: "squat",
  },
  {
    id: "reverse_lunges",
    name: "Alternating Reverse Lunge",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Quadriceps, Gluteus Maximus, Hamstrings",
    secondaryMuscles: "Adductors, Gastrocnemius, Core Balance",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Standing upright with feet hip-width apart.",
    movementPattern: "Single-leg knee flexion & step back",
    executionSteps: [
      "1. Step backward with left foot, planting toes.",
      "2. Bend both knees to 90 degrees until back knee hovers above floor.",
      "3. Press through front right heel to step forward.",
      "4. Alternate legs rhythmically.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 12,
    safetyNotes: "Keep front knee aligned over second toe and torso upright.",
    commonMistakes: ["Leaning forward", "Front knee caving inward", "Banging rear knee"],
    contraindications: ["Severe patellar tendinitis"],
    status: "approved",
    cameraPreset: "side",
    animationType: "lunge",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Quadriceps, Gluteus Maximus",
    secondaryMuscles: "Hamstrings, Core, Calves",
    difficulty: "Intermediate",
    equipment: "Chair",
    startingPosition: "Rear foot elevated on a chair, front foot forward.",
    movementPattern: "Single-leg knee-hip flexion",
    executionSteps: [
      "1. Stand 2 feet in front of a chair. Place rear foot on the seat behind you.",
      "2. Lower body by bending front knee until thigh is parallel to floor.",
      "3. Drive through front heel to stand back up.",
      "4. Complete all reps on one side before switching.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Keep torso upright. Front knee should not go past toes excessively.",
    commonMistakes: ["Leaning forward", "Front knee caving in", "Bouncing at bottom"],
    contraindications: ["Knee instability", "Hip flexor strain"],
    status: "approved",
    cameraPreset: "side",
    animationType: "lunge",
  },
  {
    id: "wall_sit",
    name: "Wall Sit Hold",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Quadriceps, Gluteus Maximus",
    secondaryMuscles: "Calves, Core",
    difficulty: "Beginner",
    equipment: "Wall",
    startingPosition: "Back flat against wall, sliding down until thighs are parallel.",
    movementPattern: "Isometric knee-hip hold",
    executionSteps: [
      "1. Stand with back flat against a wall.",
      "2. Slide down until thighs are parallel to floor.",
      "3. Keep knees directly above ankles.",
      "4. Hold the position for the target duration.",
    ],
    tempo: "Isometric",
    recommendedDuration: 45,
    safetyNotes: "Keep back flat against wall. Do not let knees cave inward.",
    commonMistakes: ["Knees going past toes", "Sliding down too low", "Arching lower back"],
    contraindications: ["Severe knee osteoarthritis", "Acute patellar injury"],
    status: "approved",
    cameraPreset: "side",
    animationType: "squat",
  },
  {
    id: "calf_raises",
    name: "Standing Calf Raises",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Gastrocnemius, Soleus",
    secondaryMuscles: "Tibialis Anterior",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Standing upright, feet hip-width apart, near a wall for balance.",
    movementPattern: "Ankle plantar flexion",
    executionSteps: [
      "1. Stand tall with feet hip-width apart.",
      "2. Push through the balls of your feet to raise heels off the ground.",
      "3. Squeeze calves at the top for 1 second.",
      "4. Lower heels back down slowly.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 20,
    safetyNotes: "Use a wall or chair for balance if needed.",
    commonMistakes: ["Bouncing at the bottom", "Not fully extending at top", "Rushing reps"],
    contraindications: ["Achilles tendinitis", "Severe ankle instability"],
    status: "approved",
    cameraPreset: "side",
    animationType: "squat",
  },
  {
    id: "glute_bridge",
    name: "Single-Leg Glute Bridge",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Gluteus Maximus, Hamstrings",
    secondaryMuscles: "Core, Erector Spinae",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying on back, one knee bent with foot flat, other leg extended.",
    movementPattern: "Hip extension with unilateral support",
    executionSteps: [
      "1. Lie on your back with one knee bent and foot flat on floor.",
      "2. Extend the other leg toward the ceiling.",
      "3. Drive through the grounded heel to lift hips up.",
      "4. Squeeze glutes at the top and lower slowly.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 12,
    safetyNotes: "Do not hyperextend the lower back at the top.",
    commonMistakes: ["Pushing through toes instead of heel", "Hyperextending back", "Dropping hips"],
    contraindications: ["Severe lower back pain", "Hamstring tear"],
    status: "approved",
    cameraPreset: "side",
    animationType: "plank",
  },
  {
    id: "sumo_squats",
    name: "Sumo Squat",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Inner Thighs (Adductors), Quadriceps, Glutes",
    secondaryMuscles: "Calves, Core",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Wide stance, toes pointed outward 45 degrees.",
    movementPattern: "Wide-stance vertical squat",
    executionSteps: [
      "1. Stand with feet wider than shoulder-width, toes pointed out.",
      "2. Lower body by bending knees and pushing hips back.",
      "3. Descend until thighs are parallel to floor.",
      "4. Push through heels to stand back up.",
    ],
    tempo: "3-1-1-1",
    recommendedReps: 15,
    safetyNotes: "Keep knees tracking over toes. Maintain upright torso.",
    commonMistakes: ["Knees caving inward", "Leaning too far forward", "Rising on toes"],
    contraindications: ["Hip adductor strain", "Knee pain"],
    status: "approved",
    cameraPreset: "front",
    animationType: "squat",
  },
  {
    id: "lateral_lunges",
    name: "Lateral Lunge",
    category: "Strength",
    bodyPart: "Legs",
    targetMuscles: "Adductors, Quadriceps, Gluteus Maximus",
    secondaryMuscles: "Hamstrings, Calves",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Standing with feet together, hands at chest.",
    movementPattern: "Lateral step with knee-hip flexion",
    executionSteps: [
      "1. Step wide to the right, keeping left leg straight.",
      "2. Bend right knee and push hips back, keeping chest up.",
      "3. Descend until right thigh is near parallel.",
      "4. Push off right foot to return to center, alternate sides.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Keep the straight leg's foot flat on the floor.",
    commonMistakes: ["Rising on toes of bent leg", "Rounding back", "Not going deep enough"],
    contraindications: ["Groin strain", "Hip impingement"],
    status: "approved",
    cameraPreset: "front",
    animationType: "lunge",
  },
  {
    id: "jump_squats",
    name: "Jump Squat",
    category: "Cardio",
    bodyPart: "Legs",
    targetMuscles: "Quadriceps, Gluteus Maximus, Calves",
    secondaryMuscles: "Hamstrings, Core",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Feet shoulder-width apart, standing tall.",
    movementPattern: "Explosive squat with vertical jump",
    executionSteps: [
      "1. Lower into a squat position.",
      "2. Explode upward jumping as high as possible.",
      "3. Land softly on balls of feet, absorbing impact.",
      "4. Immediately descend into the next squat.",
    ],
    tempo: "Explosive",
    recommendedReps: 12,
    safetyNotes: "Land softly. Avoid if you have knee or ankle issues.",
    commonMistakes: ["Heavy landing", "Not squatting deep enough", "Knees caving on landing"],
    contraindications: ["Knee injuries", "Ankle instability", "Pregnancy"],
    status: "approved",
    cameraPreset: "three_quarter",
    animationType: "squat",
  },

  // ==================== FULL BODY ====================
  {
    id: "plank_hold",
    name: "Forearm Core Plank",
    category: "Core",
    bodyPart: "Full Body",
    targetMuscles: "Transverse Abdominis, Rectus Abdominis, Obliques",
    secondaryMuscles: "Gluteus Maximus, Quadriceps, Shoulders",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Forearms grounded, elbows under shoulders, body in a straight line.",
    movementPattern: "Isometric core stability hold",
    executionSteps: [
      "1. Place elbows beneath shoulders with forearms flat.",
      "2. Extend legs backward on toes, locking hips in line with shoulders.",
      "3. Pull belly button toward spine and squeeze glutes.",
      "4. Maintain steady breathing for the duration.",
    ],
    tempo: "Isometric",
    recommendedDuration: 45,
    safetyNotes: "Do not let lower back arch or hips lift excessively high.",
    commonMistakes: ["Sagging lower back", "Holding breath", "Piking hips"],
    contraindications: ["Uncontrolled high blood pressure", "Severe lumbar hernia"],
    status: "approved",
    cameraPreset: "side",
    animationType: "plank",
  },
  {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    category: "Cardio",
    bodyPart: "Full Body",
    targetMuscles: "Rectus Abdominis, Hip Flexors, Anterior Deltoids",
    secondaryMuscles: "Chest, Obliques, Calves",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "High push-up plank with arms extended under shoulders.",
    movementPattern: "Alternating rapid knee drives",
    executionSteps: [
      "1. Maintain rigid high plank over wrists.",
      "2. Drive right knee forward toward chest.",
      "3. Quickly switch legs, driving left knee forward.",
      "4. Run continuously with a rapid rhythm.",
    ],
    tempo: "Fast Cadence",
    recommendedDuration: 30,
    safetyNotes: "Keep shoulders over wrists and hips level.",
    commonMistakes: ["Piking hips into air", "Bouncing upper body"],
    contraindications: ["Wrist arthritis", "Acute hip flexor strain"],
    status: "approved",
    cameraPreset: "side",
    animationType: "mountain_climbers",
  },
  {
    id: "bicycle_crunches",
    name: "Bicycle Crunches",
    category: "Core",
    bodyPart: "Full Body",
    targetMuscles: "Rectus Abdominis, Obliques, Hip Flexors",
    secondaryMuscles: "Serratus Anterior",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying on back, hands behind head, legs raised with knees bent.",
    movementPattern: "Alternating torso rotation with leg extension",
    executionSteps: [
      "1. Lie on back with hands lightly behind head.",
      "2. Lift shoulder blades off the floor.",
      "3. Rotate torso bringing right elbow toward left knee while extending right leg.",
      "4. Alternate sides in a pedaling motion.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 20,
    safetyNotes: "Do not pull on the neck. Rotate from the torso, not the elbows.",
    commonMistakes: ["Pulling on neck", "Moving too fast", "Not rotating enough"],
    contraindications: ["Neck injuries", "Severe lower back pain"],
    status: "approved",
    cameraPreset: "side",
    animationType: "crunch",
  },
  {
    id: "leg_raises",
    name: "Lying Leg Raises",
    category: "Core",
    bodyPart: "Full Body",
    targetMuscles: "Lower Rectus Abdominis, Hip Flexors",
    secondaryMuscles: "Obliques, Quadriceps",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Lying flat on back, hands under glutes for support.",
    movementPattern: "Hip flexion with core stabilization",
    executionSteps: [
      "1. Lie flat on back with legs straight, hands under glutes.",
      "2. Keeping legs straight, raise them until perpendicular to floor.",
      "3. Lower legs slowly until they hover just above the floor.",
      "4. Repeat without letting lower back lift off the ground.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 12,
    safetyNotes: "Press lower back into the floor throughout. Bend knees if needed.",
    commonMistakes: ["Arching lower back", "Using momentum", "Bending knees excessively"],
    contraindications: ["Lower back hernia", "Hip flexor injury"],
    status: "approved",
    cameraPreset: "side",
    animationType: "crunch",
  },
  {
    id: "russian_twists",
    name: "Russian Twists",
    category: "Core",
    bodyPart: "Full Body",
    targetMuscles: "Obliques, Rectus Abdominis",
    secondaryMuscles: "Hip Flexors, Erector Spinae",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Seated, knees bent, feet slightly off floor, torso leaning back 45 degrees.",
    movementPattern: "Seated torso rotation",
    executionSteps: [
      "1. Sit with knees bent and feet slightly elevated.",
      "2. Lean torso back to 45 degrees while keeping spine straight.",
      "3. Rotate torso to the right, touching floor beside hip.",
      "4. Rotate to the left side and continue alternating.",
    ],
    tempo: "1-1-1-1",
    recommendedReps: 20,
    safetyNotes: "Keep spine straight and chest lifted throughout.",
    commonMistakes: ["Rounding the back", "Moving only the arms", "Feet touching floor"],
    contraindications: ["Lower back injuries", "Spinal disc issues"],
    status: "approved",
    cameraPreset: "three_quarter",
    animationType: "crunch",
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    category: "Core",
    bodyPart: "Full Body",
    targetMuscles: "Transverse Abdominis, Rectus Abdominis",
    secondaryMuscles: "Hip Flexors, Obliques",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying on back, arms extended toward ceiling, knees bent at 90 degrees.",
    movementPattern: "Contralateral limb extension with core stabilization",
    executionSteps: [
      "1. Lie on back with arms up and knees bent at 90 degrees.",
      "2. Press lower back firmly into the floor.",
      "3. Slowly extend right arm overhead and left leg straight out simultaneously.",
      "4. Return to start and repeat on the opposite side.",
    ],
    tempo: "3-1-3-1",
    recommendedReps: 10,
    safetyNotes: "The lower back must stay pressed into the floor at all times.",
    commonMistakes: ["Arching lower back", "Moving too fast", "Extending limbs too far"],
    contraindications: ["Severe lower back pain"],
    status: "approved",
    cameraPreset: "side",
    animationType: "crunch",
  },
  {
    id: "side_plank",
    name: "Side Plank Hold",
    category: "Core",
    bodyPart: "Full Body",
    targetMuscles: "Obliques, Transverse Abdominis",
    secondaryMuscles: "Shoulders, Gluteus Medius",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying on side, forearm on ground, body in a straight line.",
    movementPattern: "Isometric lateral core hold",
    executionSteps: [
      "1. Lie on your side with forearm on the ground, elbow under shoulder.",
      "2. Stack feet on top of each other.",
      "3. Lift hips off the floor forming a straight line from head to feet.",
      "4. Hold the position for the target duration.",
    ],
    tempo: "Isometric",
    recommendedDuration: 30,
    safetyNotes: "Keep hips lifted and body in a straight line.",
    commonMistakes: ["Hips dropping", "Shoulder collapsing", "Holding breath"],
    contraindications: ["Shoulder injury", "Oblique strain"],
    status: "approved",
    cameraPreset: "front",
    animationType: "plank",
  },
  {
    id: "toe_touches",
    name: "Lying Toe Touches",
    category: "Core",
    bodyPart: "Full Body",
    targetMuscles: "Upper Rectus Abdominis",
    secondaryMuscles: "Obliques, Hip Flexors",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying on back, legs straight up toward ceiling.",
    movementPattern: "Upper abdominal crunch toward toes",
    executionSteps: [
      "1. Lie on back and extend legs straight up toward the ceiling.",
      "2. Reach both hands toward your toes.",
      "3. Lift shoulder blades off the floor using your abs.",
      "4. Lower slowly and repeat.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 15,
    safetyNotes: "Keep the movement controlled. Do not use momentum.",
    commonMistakes: ["Using momentum", "Lifting entire back off floor", "Bending knees too much"],
    contraindications: ["Lower back pain", "Neck injuries"],
    status: "approved",
    cameraPreset: "side",
    animationType: "crunch",
  },

  // ==================== SHOULDERS ====================
  {
    id: "pike_pushups",
    name: "Pike Push-Up",
    category: "Strength",
    bodyPart: "Shoulders",
    targetMuscles: "Anterior Deltoids, Lateral Deltoids, Triceps",
    secondaryMuscles: "Upper Chest, Core",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "Downward dog position with hips high and hands on floor.",
    movementPattern: "Vertical push from inverted position",
    executionSteps: [
      "1. Start in downward dog with hips elevated high.",
      "2. Bend elbows to lower the top of your head toward the floor.",
      "3. Press back up to full arm extension.",
      "4. Keep hips elevated throughout the movement.",
    ],
    tempo: "2-1-1-1",
    recommendedReps: 10,
    safetyNotes: "Keep head between arms. Do not let elbows flare excessively.",
    commonMistakes: ["Not enough hip elevation", "Elbows flaring", "Not going deep enough"],
    contraindications: ["Shoulder impingement", "High blood pressure"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },
  {
    id: "plank_shoulder_taps",
    name: "Plank Shoulder Taps",
    category: "Core",
    bodyPart: "Shoulders",
    targetMuscles: "Deltoids, Core Stability, Rotator Cuff",
    secondaryMuscles: "Chest, Triceps, Obliques",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "High plank position, hands under shoulders.",
    movementPattern: "Unilateral shoulder tap with anti-rotation",
    executionSteps: [
      "1. Start in high plank with hands under shoulders.",
      "2. Lift right hand and tap left shoulder.",
      "3. Return hand to floor with control.",
      "4. Repeat on the other side, minimizing hip movement.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 16,
    safetyNotes: "Keep hips as still as possible. Widen feet for more stability.",
    commonMistakes: ["Excessive hip rocking", "Placing hands too far forward", "Rushing"],
    contraindications: ["Shoulder instability", "Wrist injuries"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },
  {
    id: "bear_crawl",
    name: "Bear Crawl",
    category: "Cardio",
    bodyPart: "Shoulders",
    targetMuscles: "Deltoids, Core, Quadriceps",
    secondaryMuscles: "Triceps, Hip Flexors, Calves",
    difficulty: "Intermediate",
    equipment: "No equipment",
    startingPosition: "All fours with knees hovering 1 inch off the ground.",
    movementPattern: "Contralateral crawling movement",
    executionSteps: [
      "1. Start on all fours with knees 1 inch off the ground.",
      "2. Step forward with right hand and left foot simultaneously.",
      "3. Follow with left hand and right foot.",
      "4. Continue crawling forward, keeping hips low and level.",
    ],
    tempo: "Steady",
    recommendedDuration: 30,
    safetyNotes: "Keep knees close to the ground. Keep back flat.",
    commonMistakes: ["Hips too high", "Knees touching ground", "Moving same-side limbs"],
    contraindications: ["Wrist injuries", "Shoulder pain"],
    status: "approved",
    cameraPreset: "side",
    animationType: "mountain_climbers",
  },
  {
    id: "inchworm",
    name: "Inchworm Walk-Out",
    category: "Mobility",
    bodyPart: "Shoulders",
    targetMuscles: "Deltoids, Core, Hamstrings",
    secondaryMuscles: "Chest, Triceps, Calves",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Standing upright, feet hip-width apart.",
    movementPattern: "Walk-out to plank and back",
    executionSteps: [
      "1. Stand tall, hinge at hips and place hands on floor.",
      "2. Walk hands forward until you reach a high plank position.",
      "3. Pause for 1 second in plank.",
      "4. Walk hands back toward feet and stand up.",
    ],
    tempo: "Slow and controlled",
    recommendedReps: 8,
    safetyNotes: "Keep legs as straight as possible to stretch hamstrings.",
    commonMistakes: ["Bending knees too much", "Rushing the walk-out", "Sagging hips in plank"],
    contraindications: ["Hamstring tears", "Wrist injuries"],
    status: "approved",
    cameraPreset: "side",
    animationType: "stretching",
  },
  {
    id: "crab_reach",
    name: "Crab Reach",
    category: "Mobility",
    bodyPart: "Shoulders",
    targetMuscles: "Deltoids, Thoracic Spine, Hip Flexors",
    secondaryMuscles: "Glutes, Triceps, Core",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Reverse tabletop (crab) position with hands and feet on floor.",
    movementPattern: "Thoracic rotation with overhead reach",
    executionSteps: [
      "1. Start in reverse tabletop with hands behind you, fingers toward feet.",
      "2. Lift hips up toward the ceiling.",
      "3. Reach right arm overhead and rotate torso to the left.",
      "4. Return to start and alternate sides.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 8,
    safetyNotes: "Keep the movement smooth. Do not force the rotation.",
    commonMistakes: ["Not lifting hips high enough", "Rushing the rotation", "Shoulder pain from poor hand placement"],
    contraindications: ["Shoulder impingement", "Severe thoracic kyphosis"],
    status: "approved",
    cameraPreset: "side",
    animationType: "stretching",
  },

  // ==================== BACK ====================
  {
    id: "cat_cow_stretch",
    name: "Cat-Cow Stretch",
    category: "Mobility",
    bodyPart: "Back",
    targetMuscles: "Spinal Erectors, Thoracic Spine, Cervical Spine",
    secondaryMuscles: "Abdominals, Neck",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "All-fours position with hands under shoulders, knees under hips.",
    movementPattern: "Spinal flexion & extension",
    executionSteps: [
      "1. Exhale and arch spine upward like a cat, tucking chin.",
      "2. Inhale and gently lower belly toward floor while lifting chest.",
      "3. Flow smoothly between cat and cow postures.",
    ],
    tempo: "Slow Breathing",
    recommendedDuration: 60,
    safetyNotes: "Move gently within pain-free range of motion.",
    commonMistakes: ["Forcing neck hyper-extension", "Moving too quickly"],
    contraindications: ["Fresh spinal surgery"],
    status: "approved",
    cameraPreset: "side",
    animationType: "stretching",
  },
  {
    id: "superman_hold",
    name: "Superman Hold",
    category: "Strength",
    bodyPart: "Back",
    targetMuscles: "Erector Spinae, Gluteus Maximus, Rear Deltoids",
    secondaryMuscles: "Hamstrings, Upper Back",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying face down, arms extended overhead.",
    movementPattern: "Simultaneous spinal & hip extension",
    executionSteps: [
      "1. Lie face down with arms extended overhead.",
      "2. Simultaneously lift arms, chest, and legs off the floor.",
      "3. Hold the top position, squeezing glutes and lower back.",
      "4. Lower slowly back to starting position.",
    ],
    tempo: "2-2-2-1",
    recommendedReps: 12,
    safetyNotes: "Lift only as high as comfortable. Keep the neck neutral.",
    commonMistakes: ["Jerking up", "Overextending the neck", "Not lifting legs"],
    contraindications: ["Severe lumbar hernia", "Pregnancy"],
    status: "approved",
    cameraPreset: "side",
    animationType: "plank",
  },
  {
    id: "bird_dog",
    name: "Bird-Dog",
    category: "Core",
    bodyPart: "Back",
    targetMuscles: "Erector Spinae, Gluteus Maximus, Core",
    secondaryMuscles: "Rear Deltoids, Hamstrings",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "All-fours position with hands under shoulders, knees under hips.",
    movementPattern: "Contralateral limb extension with anti-rotation",
    executionSteps: [
      "1. Start on all fours with neutral spine.",
      "2. Extend right arm forward and left leg backward simultaneously.",
      "3. Hold for 2 seconds, keeping hips level.",
      "4. Return to start and repeat on opposite side.",
    ],
    tempo: "2-2-2-1",
    recommendedReps: 10,
    safetyNotes: "Keep hips square to the floor. Do not arch the lower back.",
    commonMistakes: ["Hip rotation", "Arching lower back", "Looking up"],
    contraindications: ["Severe lower back pain", "Knee injuries"],
    status: "approved",
    cameraPreset: "side",
    animationType: "plank",
  },
  {
    id: "reverse_snow_angels",
    name: "Reverse Snow Angels",
    category: "Strength",
    bodyPart: "Back",
    targetMuscles: "Rhomboids, Rear Deltoids, Lower Traps",
    secondaryMuscles: "Erector Spinae, Rotator Cuff",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying face down, arms at sides, palms facing down.",
    movementPattern: "Scapular retraction with arm abduction/adduction",
    executionSteps: [
      "1. Lie face down with arms at your sides, palms down.",
      "2. Lift chest slightly off the floor.",
      "3. Sweep arms out to the sides and overhead in an arc, like a snow angel.",
      "4. Bring arms back to your sides, squeezing shoulder blades together.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 12,
    safetyNotes: "Keep the movement slow and controlled. Squeeze at the bottom.",
    commonMistakes: ["Rushing through reps", "Lifting chest too high", "Not squeezing shoulder blades"],
    contraindications: ["Shoulder impingement", "Neck injuries"],
    status: "approved",
    cameraPreset: "side",
    animationType: "plank",
  },
  {
    id: "wall_angels",
    name: "Wall Angels",
    category: "Mobility",
    bodyPart: "Back",
    targetMuscles: "Rhomboids, Lower Traps, Rotator Cuff",
    secondaryMuscles: "Erector Spinae, Posterior Deltoids",
    difficulty: "Beginner",
    equipment: "Wall",
    startingPosition: "Standing with back flat against wall, arms in goal-post position.",
    movementPattern: "Scapular retraction with wall-guided arm movement",
    executionSteps: [
      "1. Stand with back, head, and arms flat against a wall.",
      "2. Place arms in a goal-post position (elbows at 90 degrees).",
      "3. Slide arms up the wall overhead while maintaining contact.",
      "4. Slide arms back down to the starting position.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 10,
    safetyNotes: "Keep lower back pressed into the wall throughout.",
    commonMistakes: ["Lower back peeling off wall", "Arms losing wall contact", "Rushing"],
    contraindications: ["Severe thoracic kyphosis", "Shoulder pain"],
    status: "approved",
    cameraPreset: "front",
    animationType: "stretching",
  },
  {
    id: "scapular_pushups",
    name: "Scapular Push-Up",
    category: "Strength",
    bodyPart: "Back",
    targetMuscles: "Serratus Anterior, Rhomboids, Lower Traps",
    secondaryMuscles: "Core, Pectoralis Minor",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "High plank position with arms locked straight.",
    movementPattern: "Scapular protraction & retraction",
    executionSteps: [
      "1. Start in a high plank with arms fully extended.",
      "2. Let your chest sink between your shoulder blades (retraction).",
      "3. Push your upper back toward the ceiling by spreading shoulder blades (protraction).",
      "4. Repeat without bending elbows.",
    ],
    tempo: "2-1-2-1",
    recommendedReps: 12,
    safetyNotes: "Keep elbows completely straight throughout the movement.",
    commonMistakes: ["Bending elbows", "Moving too fast", "Not enough range"],
    contraindications: ["Shoulder instability", "Scapular winging"],
    status: "approved",
    cameraPreset: "side",
    animationType: "pushup",
  },
  {
    id: "prone_cobra",
    name: "Prone Cobra Hold",
    category: "Strength",
    bodyPart: "Back",
    targetMuscles: "Erector Spinae, Rear Deltoids, Glutes",
    secondaryMuscles: "Hamstrings, Rhomboids",
    difficulty: "Beginner",
    equipment: "No equipment",
    startingPosition: "Lying face down, arms at sides, forehead on floor.",
    movementPattern: "Isometric spinal extension hold",
    executionSteps: [
      "1. Lie face down with arms at sides, palms down.",
      "2. Lift chest, arms, and legs off the floor.",
      "3. Turn thumbs outward and squeeze shoulder blades together.",
      "4. Hold for the target duration.",
    ],
    tempo: "Isometric",
    recommendedDuration: 30,
    safetyNotes: "Keep the neck neutral. Do not hyperextend the lower back.",
    commonMistakes: ["Looking up (straining neck)", "Not lifting high enough", "Holding breath"],
    contraindications: ["Severe lower back pain", "Pregnancy"],
    status: "approved",
    cameraPreset: "side",
    animationType: "plank",
  },
];

export function getExerciseById(id: string): DetailedExercise {
  const found = DETAILED_EXERCISE_DATABASE.find((ex) => ex.id === id);
  if (found) return found;
  return DETAILED_EXERCISE_DATABASE[0];
}

export function getExercisesByBodyPart(bodyPart: string): DetailedExercise[] {
  return DETAILED_EXERCISE_DATABASE.filter((ex) => ex.bodyPart === bodyPart);
}

export function searchExercises(query: string, category?: string): DetailedExercise[] {
  return DETAILED_EXERCISE_DATABASE.filter((ex) => {
    const matchesQuery =
      !query ||
      ex.name.toLowerCase().includes(query.toLowerCase()) ||
      ex.targetMuscles.toLowerCase().includes(query.toLowerCase());
    const matchesCategory = !category || category === "All" || ex.category === category;
    return matchesQuery && matchesCategory;
  });
}
